version: '3'

services:
  db:
    image: mariadb:10.11
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW --max-connections=2000 --innodb-read-only-compressed=OFF
    restart: always
    volumes:
      - db:/var/lib/mysql
    networks:
      - backend

  app:  
    image: nextcloud:26-apache
    restart: always
    volumes:
      - nextcloud:/var/www/html
    depends_on:
      - db
    networks:
      - frontend
      - backend

volumes:
  db:
  nextcloud:

networks:
  frontend:
  backend:
    internal: true
