version: '3'

services:
  db:
    image: mariadb
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW --max-connections=2000
    restart: always
    volumes:
      - db:/var/lib/mysql
    networks:
      - backend

  app:  
    image: nextcloud:apache
    restart: always
    volumes:
      - nextcloud:/var/www/html
    depends_on:
      - db
    networks:
      - frontend
      - backend

volumes:
  db:
  nextcloud:

networks:
  frontend:
    external:
      name: proxy_frontend
  backend:
