version: '3'

services:
  db:
    environment:
      - MYSQL_PASSWORD=<password>
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_ROOT_PASSWORD=<password>

  app:
    environment:
      - MYSQL_HOST=db
